MODINV-657 Fix creating holdings via data import
folio-org/mod-inventory pull request #489
Opened 2022-03-15 12:45 UTC by ALiemeshka

### Purpose
Fix creating holdings via data import

### Approach
add to CreateMarcHoldingsEventHandler logic for set sourceId.

### Learning
[MODINV-657](https://issues.folio.org/browse/MODINV-657)

2022-03-15 14:33 UTC, psmagin requested changes

2022-03-15 14:33 UTC, psmagin commented on src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandler.java
> +          promise.complete(sourceId);
```suggestion
          if (findResult.getResult() != null && findResult.getResult().totalRecords == 1){
            var sourceId = findResult.getResult().records.get(0).getId();
            promise.complete(sourceId);
          } else {
            promise.fail(new EventProcessingException("No source id found for holdings with name MARC"));
          }
```

2022-03-16 08:48 UTC, psmagin approved these changes

2022-03-16 11:30 UTC, viacheslavkol approved these changes

2022-03-16 11:39 UTC, merged